name: firebase_auth_example
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.20
  cloud_firestore: ^3.1.18
  firebase_core: ^1.18.0
  # google_sign_in: ^5.3.3
  email_validator: ^2.0.1
  firebase_database: ^9.0.17
  lottie: ^1.3.0
  get: 4.6.5
  flutter: 
    sdk: flutter
  image_picker: ^0.8.5+3

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true


  assets:
  - assets/signup.json
  - assets/login-and-sign-up.json
  - assets/account-created-thank-you.json
  - assets/man.png

